language: node_js
services:
  - redis-server
node_js:
  - "10.16.3"
before_script:
  - uname -a 
  - cat /etc/lsb-release
  - sudo apt-get install cabal-install
  - cabal update
  - cabal install pandoc
  - export PATH=~/.cabal/bin:$PATH
  - export BLOT_PANDOC_PATH=$(which pandoc)
  - node config/blot/setup
before_install:
  - export BLOT_PANDOC_PATH=$(which pandoc)
rvm:
  - 1.9.3
cache: npm
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8