language: node_js
services:
  - redis-server
node_js:
  - "8.12.0"
before_install:
  - export BLOT_PANDOC_PATH=$(which pandoc)
before_script:
  - export PATH=$PATH:/home/travis/.cabal/bin
  - node app/setup
cache: npm
env:
  - CXX=g++-4.8
install:
- cabal update
- cabal install pandoc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - haskell-platform
      - g++-4.8    