language: node_js
services:
  - redis-server
node_js:
  - "10.16.3"
before_install:
  - export BLOT_PANDOC_PATH=$(which pandoc)
before_script:
  - node app/setup
cache: npm
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pandoc
      - g++-4.8    