language: node_js
services:
  - redis-server
node_js:
  - "8.12.0"
before_install:
  - export BLOT_PANDOC_PATH=$(which pandoc)
before_script:
  - node app/setup
  - uname -a 
  - cat /etc/lsb-release
  - sudo apt-get install cabal-install
  - cabal update
  - cabal install pandoc
  - export PATH=~/.cabal/bin:$PATH
rvm:
  - 1.9.3
cache: npm
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8    