language: 
  - node_js
  - python
services:
  - redis-server
python:
  - "2.7"  
node_js:
  - "8.12.0"
before_install:
  - export BLOT_PANDOC_PATH=$(which pandoc)
install:
  - pip install -r app/clients/dropbox/tests/util/webhook/requirements.txt
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pandoc
      - g++-4.8    