language: 
  - node_js
services:
  - redis-server
node_js:
  - "8.12.0"
before_install:
  - export BLOT_PANDOC_PATH=$(which pandoc)
  - python --version
install:
  - pip install pyopenssl
  - pip install click
  - pip install requests
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python-minimal
      - pandoc
      - g++-4.8    