name: Format code

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run code formatting tool
        uses: davidmerfield/prettier_action@3.4
        with:
          prettier_version: 2.0.5
          prettier_options: --write **/*.js !app/*/views !app/templates !app/build/plugins/*/public.js !scripts/state
          commit_message: Auto-formatted code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: format-code
          delete-branch: true
          title: Automated code formatting
          body: Runs prettier on master branch.