# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        redis-version: [4]

    env:
      BLOT_CACHE: false
      BLOT_DIRECTORY: /
      BLOT_DEBUG: false
      BLOT_MAINTENANCE: false
      BLOT_PRODUCTION: true
      BLOT_PROTOCOL: https
      BLOT_ENVIRONMENT: production
      BLOT_HOST: blot.development
      BLOT_ADMIN_EMAIL: ${{ secrets.BLOT_ADMIN_EMAIL }}
      BLOT_DROPBOX_APP_SECRET: ${{ secrets.BLOT_DROPBOX_APP_SECRET }}
      BLOT_DROPBOX_FULL_SECRET: ${{ secrets.BLOT_DROPBOX_FULL_SECRET }}
      BLOT_DROPBOX_TEST_ACCOUNT_APP_TOKEN: ${{ secrets.BLOT_DROPBOX_TEST_ACCOUNT_APP_TOKEN }}
      BLOT_DROPBOX_TEST_ACCOUNT_FULL_TOKEN: ${{ secrets.BLOT_DROPBOX_TEST_ACCOUNT_FULL_TOKEN }}
      BLOT_DROPBOX_TEST_ACCOUNT_ID: ${{ secrets.BLOT_DROPBOX_TEST_ACCOUNT_ID }}
      BLOT_MAILGUN_KEY: ${{ secrets.BLOT_MAILGUN_KEY }}
      BLOT_SESSION_SECRET: ${{ secrets.BLOT_SESSION_SECRET }}
      BLOT_TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.BLOT_TWITTER_ACCESS_TOKEN_KEY }}
      BLOT_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.BLOT_TWITTER_ACCESS_TOKEN_SECRET }}
      BLOT_TWITTER_CONSUMER_KEY: ${{ secrets.BLOT_TWITTER_CONSUMER_KEY }}
      BLOT_TWITTER_CONSUMER_SECRET: ${{ secrets.BLOT_TWITTER_CONSUMER_SECRET }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}      
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.16.3' 
    
    - run: export BLOT_PANDOC_PATH=$(which pandoc)
    - run: npm ci
    - run: node config/blot/setup
    - run: npm test
