# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        BLOT_CACHE: false
        BLOT_DEBUG: false
        BLOT_MAINTENANCE: false
        BLOT_PRODUCTION: true
        BLOT_PROTOCOL: https
        BLOT_ENVIRONMENT: production
        BLOT_HOST: blot.development
        PANDOC_VERSION: 2.11.3.2
        PANDOC: $HOME/.pandoc
        PANDOC_DEB: https://github.com/jgm/pandoc/releases/download/$PANDOC_VERSION/pandoc-$PANDOC_VERSION-1-amd64.deb
    - run: mkdir -p "$PANDOC"
    - run: if [[ ! -f "$PANDOC/pandoc.deb" ]]; then curl -L "$PANDOC_DEB" > "$PANDOC/pandoc.deb" && dpkg -x "$PANDOC/pandoc.deb" "$PANDOC"; fi
    - run: export PATH="$PANDOC/usr/bin:$PATH"
    - run: export BLOT_PANDOC_PATH=$(which pandoc)
    - run: node config/blot/setup
    - run: npm ci
    - run: npm test
